
version: '3'

services: 
    web:
        container_name: seminario
        restart: always
        build: .
        ports: 
            - "8080:8080"
        links: 
            - mongo
        volumes: 
            - .:/usr/src/app
    
    mongo:
        container_name: mymongodatabase
        image: mongo
        ports: 
            - "27018:27017"
        logging: 
            driver: none